/**
 * Summary - Markdown report generator
 *
 * Generates evaluation summary in Markdown format
 */

import { EvaluationResult, MetricComparison } from '../core/evaluator';

export class SummaryGenerator {
  /**
   * Generate a full Markdown summary report
   */
  generate(result: EvaluationResult): string {
    let md = `# Skill Evolution Summary\n\n`;
    md += `**Skill:** ${result.skillName}\n`;
    md += `**Baseline Version:** ${result.baselineVersion}\n`;
    md += `**Evolved Version:** ${result.evolvedVersion}\n`;
    md += `**Evaluation Date:** ${result.timestamp.toISOString().split('T')[0]}\n\n`;

    md += `---\n\n`;
    md += `## Metrics Comparison\n\n`;
    md += this.generateMetricsTable(result.metrics);

    md += `\n---\n\n`;
    md += `## Conclusion\n\n`;
    md += result.conclusion;

    md += `\n\n---\n\n`;
    md += `> Generated by Skill-Adapter Evolution Engine\n`;

    return md;
  }

  /**
   * Generate metrics comparison table
   */
  private generateMetricsTable(metrics: MetricComparison[]): string {
    let table = `| Metric | Baseline | Evolved | Delta | Status |\n`;
    table += `| --- | --- | --- | --- | --- |\n`;

    for (const metric of metrics) {
      const statusIcon = this.getStatusIcon(metric.status);
      const deltaFormatted = this.formatDelta(metric.delta, metric.deltaType);

      table += `| **${metric.name}** | ${this.formatValue(metric.baseline, metric.name)} | ${this.formatValue(metric.evolved, metric.name)} | **${deltaFormatted}** | ${statusIcon} |\n`;
    }

    return table;
  }

  /**
   * Get status icon
   */
  private getStatusIcon(status: 'good' | 'bad' | 'neutral'): string {
    switch (status) {
      case 'good':
        return '✅';
      case 'bad':
        return '❌';
      case 'neutral':
        return '➖';
    }
  }

  /**
   * Format delta value
   */
  private formatDelta(delta: number, type: 'increase' | 'decrease' | 'unchanged'): string {
    if (type === 'unchanged') {
      return '0%';
    }
    const sign = type === 'increase' ? '+' : '';
    return `${sign}${delta.toFixed(1)}%`;
  }

  /**
   * Format metric value based on type
   */
  private formatValue(value: number, metricName: string): string {
    if (metricName.includes('Token') || metricName.includes('Context')) {
      // Format as K for large numbers
      if (value >= 1000) {
        return `${(value / 1000).toFixed(1)}k`;
      }
    }
    return value.toFixed(1);
  }

  /**
   * Generate a brief summary line
   */
  generateBriefSummary(result: EvaluationResult): string {
    const statusEmoji = result.overallStatus === 'improved' ? '✅' :
                       result.overallStatus === 'degraded' ? '❌' : '➖';

    return `${statusEmoji} ${result.skillName}: ${result.baselineVersion} → ${result.evolvedVersion} (${result.overallStatus})`;
  }
}

// Singleton instance
export const summaryGenerator = new SummaryGenerator();